theme: jekyll-theme-minimal

title: ISMIR
description: Homepage of the International Society for Music Information Retrieval
authors: ISMIR Society

menu:
  conferences:
    url: /conferences
    title: Conferences
  proceedings:
    url: /proceedings
    title: Proceedings
  resources:
    url: /resources
    title: Resources
  stats:
    url: /stats
    title: Community Statistics
  wimir:
    url: /wimir
    title: Women in MIR
  tismir:
    url: http://transactions.ismir.net/
    title: Transactions of ISMIR
  about:
    url: /about
    title: About the Society
  membership:
    url: /membership
    title: Membership
  contact:
    url: /contact
    title: Contact


exclude:
  - Gemfile
  - Gemfile.lock